### ISSUE TITLE
Release ROCKET-1 on Hugging Face

### ISSUE THREAD

**Issue by NielsRogge** [CraftJarvis/ROCKET-1#1]
Hi @phython96,

Niels here from the open-source team at Hugging Face. I discovered your work through AK's daily papers, and indexed the paper page here: https://huggingface.co/papers/2410.17856. The paper page lets people discuss the paper, and discover its artifacts (such as models, dataset, a demo in the form of a 🤗 Space).

Your paper mentions that the code and demos will be available at https://craftjarvis.github.io/ROCKET-1.  It would be great to make the ROCKET-1 model and its demo available on the 🤗 hub, to improve their discoverability/visibility. We can add tags so that people find them when filtering https://huggingface.co/models and https://huggingface.co/spaces.

## Uploading models

See here for a guide: https://huggingface.co/docs/hub/models-uploading. 

In this case, we could leverage the [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) class which adds `from_pretrained` and `push_to_hub` to any custom `nn.Module`. Alternatively, one can leverages the [hf_hub_download](https://huggingface.co/docs/huggingface_hub/en/guides/download#download-a-single-file) one-liner to download a checkpoint from the hub. 

We encourage researchers to push each model checkpoint to a separate model repository, so that things like download stats also work. We can then also link the checkpoints to the paper page.

## Uploading Space

We encourage researchers to push their demo to a separate Space so that people can try out your model directly. We can then link it to the paper page.

Let me know if you're interested/need any help regarding this!

Cheers,
Niels
ML Engineer @ HF 🤗

**Comment by phython96** [comment]
Thank you for your advice! We have uploaded the model to the huggingface!

**Comment by phython96** [comment]
@NielsRogge We have uploaded a Docker-based usable demo of Rocket-1 at https://huggingface.co/spaces/phython96/ROCKET-1-DEMO. However, we noticed that when more than one user is using this space, the request of one user gets blocked until the other user’s request is completed. This could be due to having only a single service instance. Since our environment needs to run a Minecraft instance, which can be quite resource-intensive, I’d like to ask if there’s a way to launch a separate container for each user and destroy it when they are no longer using it.

**Comment by NielsRogge** [comment]
Hi, awesome to see you leveraging the Mixin class :)

Regarding the Space, I'll ping the team for that. One solution here could be to create a Gradio demo in combination with ZeroGPU, which has features for queueing: https://www.gradio.app/guides/setting-up-a-demo-for-maximum-performance

cc'ing @hysts here
