### ISSUE TITLE
problem:assert model == self.model_id, f"Model {self.model_id} not found in current model_url {self.model_url}"

### ISSUE THREAD

**Issue by sxy971118** [CraftJarvis/ROCKET-1#3]
```
    def post_init(self):
        if self.model_url == None or self.model_url == 'huggingface':
            self.client = None
            self.load_molmo_from_hf(self.model_id)
        else:
            client = OpenAI(
                api_key=self.api_key,
                base_url=self.model_url,
            )
            models = client.models.list()
            print(models)
            model = models.data[0].id
            assert model == self.model_id, f"Model {self.model_id} not found in current model_url {self.model_url}"
            print(f"Using model {self.model_id} based on url {self.model_url}")
            self.client = client
            
```
         你好我想问一下 这个  assert model == self.model_id, f"Model {self.model_id} not found in current model_url {self.model_url}"中的self.model_id应该是什么？因为client.models.list()打印了所有的openai可以用的模型 但是在我的认知里目前model_id一直是molmo-72b-0924，所以很奇怪 openai可用的模型中应该不包括molmo，但是为什么会存在 models.data[0].id == self.model_id的情况呢？所以model_id是在什么时候发生了改变吗？ 能在百忙之中解答，非常感谢
         
          Hello I would like to ask what should be the self.model_id in this assert model == self.model_id, f “Model {self.model_id} not found in current model_url {self.model_url}”? Because client.models.list() prints all the models available to openai but to my knowledge the current model_id is always molmo-72b-0924, so I'm curious if molmo should be excluded from the models available to openai, but why is there a case where model == self.model_id? id? So did model_id change at some point? Can you answer in your busy schedule, thanks a lot!

**Comment by sxy971118** [comment]
你好我想问一下 这个  assert model == self.model_id, f"Model {self.model_id} not found in current model_url {self.model_url}"中的self.model_id应该是什么？因为client.models.list()打印了所有的openai可以用的模型 但是在我的认知里目前model_id一直是molmo-72b-0924，所以很奇怪 openai可用的模型中应该不包括molmo，但是为什么会存在 models.data[0].id == self.model_id的情况呢？所以model_id是在什么时候发生了改变吗？ 能在百忙之中解答，非常感谢


 Hello I would like to ask what should be the self.model_id in this assert model == self.model_id, f “Model {self.model_id} not found in current model_url {self.model_url}”? Because client.models.list() prints all the models available to openai but to my knowledge the current model_id is always molmo-72b-0924, so I'm curious if molmo should be excluded from the models available to openai, but why is there a case where model == self.model_id? id? So did model_id change at some point? Can you answer in your busy schedule, thanks a lot!

**Comment by phython96** [comment]
这只是一个 OpenAI 形式的大模型访问接口，你需要用 vllm 在别的地方来部署一个 molmo 模型，然后 model_id 填你自己部署的模型id。

This is just an OpenAI-style large model access interface. You need to deploy a molmo model elsewhere using vllm, and then fill in the model_id with the ID of your own deployed model.

**Comment by sxy971118** [comment]
> 这只是一个 OpenAI 形式的大模型访问接口，你需要用 vllm 在别的地方来部署一个 molmo 模型，然后 model_id 填你自己部署的模型id。
> 
> This is just an OpenAI-style large model access interface. You need to deploy a molmo model elsewhere using vllm, and then fill in the model_id with the ID of your own deployed model.

谢谢您 ！我还有一个问题 gpt-4o用于任务分解 是在代码哪个部分进行的呢？因为我一开始以为Openai调用的是 gpt-4o，但是知道了是用Openai调用部署的molmo模型以后 对在什么时候调用gpt-4o进行任务分解感到好奇。
Thank you ! I have another question: In which part of the code is gpt-4o used for task decomposition? Because I thought Openai called gpt-4o at first, but after knowing that it was deployed with Openai calls to the molmo model was curious about at what point gpt-4o was called for task decomposition.

**Comment by phython96** [comment]
GPT-4o + Molmo + SAM + ROCKET-1 的完整架构组合还没被有开源。我们目前正在重构，不久后我们将开源一个完整的 Minecraft Agent 开发套件，届时应该会开源这部分代码。

不过这部分代码应该不复杂，您可以自己实现一个简单的版本，即以一定的频率（如 100 帧为间隔）运行 GPT-4o 判断当前是否完成任务，是否要 plan 新的任务。

The complete architecture combination of GPT-4o + Molmo + SAM + ROCKET-1 has not been open-sourced yet. We are currently restructuring, and we will soon open-source a complete Minecraft Agent development kit (soon), at which point this part of the code should be released.

However, this part of the code shouldn't be complicated; you can implement a simple version yourself by running GPT-4o at a certain frequency (for example, every 100 frames) to determine whether the current task is completed or if it needs to plan a new task.

**Comment by sxy971118** [comment]
> GPT-4o + Molmo + SAM + ROCKET-1 的完整架构组合还没被有开源。我们目前正在重构，不久后我们将开源一个完整的 Minecraft Agent 开发套件，届时应该会开源这部分代码。
> 
> 不过这部分代码应该不复杂，您可以自己实现一个简单的版本，即以一定的频率（如 100 帧为间隔）运行 GPT-4o 判断当前是否完成任务，是否要 plan 新的任务。
> 
> The complete architecture combination of GPT-4o + Molmo + SAM + ROCKET-1 has not been open-sourced yet. We are currently restructuring, and we will soon open-source a complete Minecraft Agent development kit (soon), at which point this part of the code should be released.
> 
> However, this part of the code shouldn't be complicated; you can implement a simple version yourself by running GPT-4o at a certain frequency (for example, every 100 frames) to determine whether the current task is completed or if it needs to plan a new task.

Thank you very much！ all the best！
